#!/bin/bash
# ================================================================
# Vibe Portal Deploy Guard
# Pre-deploy validation. Blocks deploy on misconfiguration.
# Outputs LLM-friendly error messages for Claude Code / Cursor.
# ================================================================
# Usage: bash scripts/vibe-deploy-guard.sh [dev|prod]
# CI/CD vars: VIBE_DEV_PORT, VIBE_PROD_PORT, VIBE_INTERNAL_PORT
#
# Auto-generated by Vibe Portal. Do not delete.
# ================================================================

set -euo pipefail

MODE="${1:-dev}"
ERRORS=0
APP_NAME="ssg-m-hub"
INTERNAL_PORT="80"
COMPOSE_FILE="docker-compose.${MODE}.yml"
if [ "$MODE" = "prod" ]; then
  COMPOSE_FILE="docker-compose.production.yml"
fi

error() {
  ERRORS=$((ERRORS + 1))
  echo ""
  echo "================================================================"
  echo "  [Vibe Portal Deploy Guard] ERROR #${ERRORS}"
  echo "================================================================"
  echo ""
  echo "  Issue: $1"
  echo ""
  if [ -n "${2:-}" ]; then echo "  Current: $2"; fi
  if [ -n "${3:-}" ]; then echo "  Expected: $3"; fi
  echo ""
  echo "  Fix:"
  echo "  $4"
  echo ""
  if [ -n "${5:-}" ]; then echo "  File: $5"; fi
  echo ""
  echo "  ---------------------------------------------------------"
  echo "  Copy this entire error and paste it into Claude Code or"
  echo "  Cursor to get an automated fix."
  echo "  ---------------------------------------------------------"
  echo ""
}

warn() {
  echo "[vibe-guard] WARNING: $1"
}

ok() {
  echo "[vibe-guard] OK: $1"
}

# ================================================================
# 1. Required files
# ================================================================

if [ ! -f Dockerfile ]; then
  error \
    "Dockerfile is missing" \
    "" "" \
    "Create a Dockerfile in the project root. If deleted, restore: git checkout HEAD~1 -- Dockerfile" \
    "Dockerfile"
else
  ok "Dockerfile exists"
fi

if [ ! -f "$COMPOSE_FILE" ]; then
  error \
    "${COMPOSE_FILE} is missing" \
    "" "" \
    "Restore the file: git checkout HEAD~1 -- ${COMPOSE_FILE}" \
    "$COMPOSE_FILE"
else
  ok "${COMPOSE_FILE} exists"
fi

if [ ! -f ".gitlab-ci.yml" ]; then
  error \
    ".gitlab-ci.yml is missing" \
    "" "" \
    "Restore the file: git checkout HEAD~1 -- .gitlab-ci.yml" \
    ".gitlab-ci.yml"
else
  ok ".gitlab-ci.yml exists"
fi

# ================================================================
# 2. Port validation (VIBE_DEV_PORT / VIBE_PROD_PORT)
# ================================================================

if [ -f "$COMPOSE_FILE" ]; then
  COMPOSE_PORT=$(grep -oP '"\K[0-9]+(?=:[0-9]+")' "$COMPOSE_FILE" 2>/dev/null | head -1 || echo "")
  if [ -z "$COMPOSE_PORT" ]; then
    COMPOSE_PORT=$(grep -oP "'\\K[0-9]+(?=:[0-9]+')" "$COMPOSE_FILE" 2>/dev/null | head -1 || echo "")
  fi
  if [ -z "$COMPOSE_PORT" ]; then
    COMPOSE_PORT=$(grep -oP '[0-9]+(?=:[0-9]+)' "$COMPOSE_FILE" 2>/dev/null | head -1 || echo "")
  fi

  COMPOSE_INTERNAL=$(grep -oP ':[0-9]+' "$COMPOSE_FILE" 2>/dev/null | head -1 | tr -d ':' || echo "")

  EXPECTED_PORT=""
  if [ "$MODE" = "dev" ] && [ -n "${VIBE_DEV_PORT:-}" ]; then
    EXPECTED_PORT="$VIBE_DEV_PORT"
  elif [ "$MODE" = "prod" ] && [ -n "${VIBE_PROD_PORT:-}" ]; then
    EXPECTED_PORT="$VIBE_PROD_PORT"
  fi

  if [ -n "$EXPECTED_PORT" ] && [ -n "$COMPOSE_PORT" ] && [ "$COMPOSE_PORT" != "$EXPECTED_PORT" ]; then
    error \
      "External port mismatch — the port in ${COMPOSE_FILE} does not match Vibe Portal" \
      "${COMPOSE_FILE} port = ${COMPOSE_PORT}" \
      "Vibe Portal registered port = ${EXPECTED_PORT}" \
      "In ${COMPOSE_FILE}, change ports: - \"${COMPOSE_PORT}:${COMPOSE_INTERNAL}\" to ports: - \"${EXPECTED_PORT}:${COMPOSE_INTERNAL}\". Ports are assigned by Vibe Portal at project creation — do not change them manually." \
      "$COMPOSE_FILE"
  elif [ -n "$EXPECTED_PORT" ] && [ -n "$COMPOSE_PORT" ]; then
    ok "External port matches (${COMPOSE_PORT})"
  fi

  if [ -n "${VIBE_INTERNAL_PORT:-}" ] && [ -n "$COMPOSE_INTERNAL" ] && [ "$COMPOSE_INTERNAL" != "$VIBE_INTERNAL_PORT" ]; then
    error \
      "Internal (container) port was changed" \
      "${COMPOSE_FILE} internal port = ${COMPOSE_INTERNAL}" \
      "Vibe Portal registered internal port = ${VIBE_INTERNAL_PORT}" \
      "In ${COMPOSE_FILE}, restore the internal port to ${VIBE_INTERNAL_PORT}. Also check Dockerfile EXPOSE and CMD --port match the same value." \
      "${COMPOSE_FILE}, Dockerfile"
  fi
fi

# ================================================================
# 3. container_name validation
# ================================================================

if [ -f "$COMPOSE_FILE" ]; then
  COMPOSE_CONTAINER=$(grep -oP 'container_name:\s*"?\K[a-zA-Z0-9_-]+' "$COMPOSE_FILE" 2>/dev/null || echo "")

  if [ -n "$COMPOSE_CONTAINER" ] && [ "$COMPOSE_CONTAINER" != "$APP_NAME" ]; then
    error \
      "container_name does not match project name" \
      "container_name = ${COMPOSE_CONTAINER}" \
      "Expected = ${APP_NAME}" \
      "In ${COMPOSE_FILE}, change container_name: \"${COMPOSE_CONTAINER}\" to container_name: \"${APP_NAME}\". Vibe Portal tracks containers by this name." \
      "$COMPOSE_FILE"
  elif [ -n "$COMPOSE_CONTAINER" ]; then
    ok "container_name matches (${APP_NAME})"
  fi
fi

# ================================================================
# 4. Dockerfile EXPOSE port
# ================================================================

if [ -f Dockerfile ]; then
  EXPOSE_PORT=$(grep -oP 'EXPOSE\s+\K[0-9]+' Dockerfile 2>/dev/null | head -1 || echo "")

  if [ -n "$EXPOSE_PORT" ] && [ -n "${VIBE_INTERNAL_PORT:-}" ] && [ "$EXPOSE_PORT" != "${VIBE_INTERNAL_PORT}" ]; then
    error \
      "Dockerfile EXPOSE port does not match registered internal port" \
      "Dockerfile EXPOSE = ${EXPOSE_PORT}" \
      "Registered internal port = ${VIBE_INTERNAL_PORT}" \
      "In Dockerfile, change EXPOSE ${EXPOSE_PORT} to EXPOSE ${VIBE_INTERNAL_PORT}. Also update ENV PORT and CMD --port to use the same value." \
      "Dockerfile"
  elif [ -n "$EXPOSE_PORT" ] && [ -n "${VIBE_INTERNAL_PORT:-}" ]; then
    ok "Dockerfile EXPOSE port matches (${EXPOSE_PORT})"
  fi
fi

# ================================================================
# 5. Image name validation
# ================================================================

if [ -f "$COMPOSE_FILE" ]; then
  COMPOSE_IMAGE=$(grep -oP 'image:\s*"?\K[a-zA-Z0-9_/-]+' "$COMPOSE_FILE" 2>/dev/null | head -1 || echo "")

  if [ -n "$COMPOSE_IMAGE" ] && [ "$COMPOSE_IMAGE" != "$APP_NAME" ] && [[ ! "$COMPOSE_IMAGE" =~ / ]]; then
    error \
      "docker-compose image name does not match project" \
      "image = ${COMPOSE_IMAGE}" \
      "Expected = ${APP_NAME}" \
      "In ${COMPOSE_FILE}, change image: \"${COMPOSE_IMAGE}:latest\" to image: \"${APP_NAME}:latest\"" \
      "$COMPOSE_FILE"
  elif [ -n "$COMPOSE_IMAGE" ]; then
    ok "Image name matches (${COMPOSE_IMAGE})"
  fi
fi

# ================================================================
# 6. .dockerignore check
# ================================================================

if [ ! -f .dockerignore ]; then
  warn "No .dockerignore found — Docker build may be slow. Exclude node_modules, .git, .env, etc."
fi

# ================================================================
# 7. .env must not be committed to git
# ================================================================

if [ -f .env ] && git ls-files --error-unmatch .env >/dev/null 2>&1; then
  error \
    ".env file is committed to git (security risk)" \
    ".env is tracked by git" \
    ".env should be in .gitignore" \
    "Run: echo '.env' >> .gitignore && git rm --cached .env && git commit -m 'fix: remove .env from git tracking'" \
    ".gitignore"
fi

# ================================================================
# Result
# ================================================================

echo ""
if [ "$ERRORS" -gt 0 ]; then
  echo "================================================================"
  echo "  Deploy Guard: ${ERRORS} error(s) found — deploy blocked"
  echo "================================================================"
  echo ""
  echo "  Copy the error messages above and paste them into"
  echo "  Claude Code or Cursor for automated fix guidance."
  echo ""
  echo "  Ports are auto-assigned by Vibe Portal at project creation."
  echo "  Changing them manually will break your service URL."
  echo ""
  echo "================================================================"
  echo ""
  exit 1
else
  echo "[vibe-guard] All checks passed — proceeding with deploy"
  echo ""
fi
